apiVersion: v1
kind: Secret
metadata:
  name: cgv-global-secrets
  namespace: cgv-prod
type: Opaque
data:
  #Các giá trị đã được mã hoá Base64:
  #Gốc : CGVPassword2026
  SPRING_DATASOURCE_PASSWORD: Q0dWUGFzc3dvcmQyMDI2
  JWT_SECRET: Uya69P2wiD7q5oLOHWiAwMQKtcSatXqOM/awvHlNHpM=
  VNPAY_HASH_SECRET: RkZUUElQU0JZUktOT1lZWUxaS0hBS09XVUJTWkdGQkM=