apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-service
  namespace: cgv-prod
  labels:
    app: booking-service
spec:
  replicas: 2 # Chạy mặc định 2 Pods để chịu tải thời gian thực (giữ ghế Redis, Kafka)
  selector:
    matchLabels:
      app: booking-service
  template:
    metadata:
      labels:
        app: booking-service
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
        - name: booking-service
          image: 313078327818.dkr.ecr.ap-southeast-1.amazonaws.com/cgv/booking-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8082
          envFrom:
            - configMapRef:
                name: cgv-global-config
            - secretRef:
                name: cgv-global-secrets
          resources:
            requests:
              cpu: "200m"
              memory: "250Mi"
            limits:
              cpu: "1000m"
              memory: "750Mi"
          startupProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 20
            periodSeconds: 10
            failureThreshold: 30
          readinessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8082
            initialDelaySeconds: 30
            periodSeconds: 15
