apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: booking-hpa
  namespace: cgv-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: booking-service
  minReplicas: 2 # Tối thiểu 2 Pods
  maxReplicas: 4 # Tự động tăng lên tối đa 4 Pods khi khách đặt vé ồ ạt
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
