apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: cgv-prod
  labels:
    app: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      tolerations:
        - key: "CriticalAddonsOnly"
          operator: "Exists"
      containers:
        - name: payment-service
          image: 313078327818.dkr.ecr.ap-southeast-1.amazonaws.com/cgv/payment-service:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8085
          envFrom:
            - configMapRef:
                name: cgv-global-config
            - secretRef:
                name: cgv-global-secrets
          env:
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "none"
          resources:
            requests:
              cpu: "300m"
              memory: "350Mi"
            limits:
              cpu: "1000m"
              memory: "750Mi"
          startupProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 60
          readinessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8085
            initialDelaySeconds: 30
            periodSeconds: 15
            failureThreshold: 5
