server:
  port: 8087
  servlet:
    context-path: /api/v1

spring:
  application:
    name: media-service
  datasource:
    url: jdbc:postgresql://localhost:5432/cgv
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8180}/realms/${REALM:cgv-realm}/protocol/openid-connect/certs


aws:
  s3:
    region: ${AWS_REGION:ap-southeast-1}
    bucket-name: ${AWS_BUCKET_NAME}
    access-key: ${AWS_ACCESS_KEY_ID}
    secret-key: ${AWS_SECRET_ACCESS_KEY}